--1
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열 FROM TB_DEPARTMENT;
--2
SELECT DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.' "학과별 정원" FROM TB_DEPARTMENT;
--3
SELECT STUDENT_NAME, DEPARTMENT_NO, ABSENCE_YN FROM TB_STUDENT NATURAL JOIN TB_DEPARTMENT WHERE ABSENCE_YN = 'Y' AND DEPARTMENT_NO = '001' AND SUBSTR(STUDENT_SSN, 8, 1)='2';
--4
SELECT STUDENT_NAME FROM TB_STUDENT WHERE STUDENT_NO='A513079' OR STUDENT_NO='A513090' OR STUDENT_NO='A513091' OR STUDENT_NO='A513110'OR STUDENT_NO='A513119';
--5
SELECT DEPARTMENT_NAME, CATEGORY FROM TB_DEPARTMENT WHERE CAPACITY >= 20 AND CAPACITY <=30;
--6
SELECT PROFESSOR_NAME FROM TB_PROFESSOR WHERE DEPARTMENT_NO IS NULL;
--7
SELECT * FROM TB_STUDENT WHERE DEPARTMENT_NO IS NULL;
--8
SELECT CLASS_NO FROM TB_CLASS WHERE PREATTENDING_CLASS_NO IS NOT NULL;
--9
SELECT CATEGORY FROM TB_DEPARTMENT GROUP BY CATEGORY;
--10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, STUDENT_ADDRESS, ABSENCE_YN  FROM TB_STUDENT WHERE SUBSTR(STUDENT_ADDRESS, 1, 2) ='전주'AND ABSENCE_YN = 'N'AND SUBSTR(STUDENT_NO, 2, 1) = '2';


--ADDITIONAL SELECT;
--1.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도 FROM TB_STUDENT WHERE DEPARTMENT_NO = '002' ORDER BY STUDENT_NAME;
--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR WHERE LENGTH(PROFESSOR_NAME) != '3';
--3
SELECT PROFESSOR_NAME 교수이름, PROFESSOR_SSN, TRUNC((SYSDATE-TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 0, 6), 'RRMMDD'))/365) 나이 FROM TB_PROFESSOR ORDER BY TRUNC((SYSDATE-TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 0, 6), 'RRMMDD'))/365);
--4
SELECT SUBSTR(PROFESSOR_NAME, 2, 3) 이름 FROM TB_PROFESSOR;
--5
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE, STUDENT_SSN, (ENTRANCE_DATE-TO_DATE('19'||SUBSTR(STUDENT_SSN , 0, 6), 'RRMMDD'))/365 FROM TB_STUDENT WHERE (ENTRANCE_DATE-TO_DATE('19'||SUBSTR(STUDENT_SSN , 0, 6), 'RRMMDD'))/365<'18';
--6
SELECT TO_CHAR(TO_DATE(20201225),'DAY') FROM DUAL;
--7
SELECT TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD'), TO_DATE('99/10/11','RR/MM/DD'), TO_DATE('49/10/11','RR/MM/DD') FROM DUAL;
--8
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';
--9
SELECT ROUND(AVG(POINT), 1) 평점 FROM TB_STUDENT NATURAL JOIN TB_GRADE WHERE STUDENT_NO='A517178';
--10
SELECT DEPARTMENT_NO, COUNT(DEPARTMENT_NO) FROM TB_DEPARTMENT NATURAL JOIN TB_STUDENT GROUP BY DEPARTMENT_NO ORDER BY DEPARTMENT_NO; 
--11
SELECT COUNT(*) "COUNT(*)" FROM TB_STUDENT WHERE COACH_PROFESSOR_NO IS NULL;
--12
SELECT SUBSTR(TERM_NO,1,4), ROUND(AVG(POINT),1) FROM TB_GRADE WHERE STUDENT_NO='A112113' GROUP BY SUBSTR(TERM_NO,1,4) ORDER BY SUBSTR(TERM_NO,1,4);
--13
SELECT * FROM TB_DEPARTMENT D LEFT JOIN TB_STUDENT S ON (D.DEPARTMENT_NO=S.DEPARTMENT_NO) WHERE ABSENCE_YN = 'Y'  ; 
SELECT *FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_PROFESSOR tp;
SELECT COACH_PROFESSOR_NO FROM TB_STUDENT ts; 


