--1
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열 FROM TB_DEPARTMENT;
--2
SELECT DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.' "학과별 정원" FROM TB_DEPARTMENT;
--3
SELECT STUDENT_NAME, DEPARTMENT_NO, ABSENCE_YN FROM TB_STUDENT NATURAL JOIN TB_DEPARTMENT WHERE ABSENCE_YN = 'Y' AND DEPARTMENT_NO = '001' AND SUBSTR(STUDENT_SSN, 8, 1)='2';
--4
SELECT STUDENT_NAME FROM TB_STUDENT WHERE STUDENT_NO='A513079' OR STUDENT_NO='A513090' OR STUDENT_NO='A513091' OR STUDENT_NO='A513110'OR STUDENT_NO='A513119';
--5
SELECT DEPARTMENT_NAME, CATEGORY FROM TB_DEPARTMENT WHERE CAPACITY >= 20 AND CAPACITY <=30;
--6
SELECT PROFESSOR_NAME FROM TB_PROFESSOR WHERE DEPARTMENT_NO IS NULL;
--7
SELECT * FROM TB_STUDENT WHERE DEPARTMENT_NO IS NULL;
--8
SELECT CLASS_NO FROM TB_CLASS WHERE PREATTENDING_CLASS_NO IS NOT NULL;
--9
SELECT CATEGORY FROM TB_DEPARTMENT GROUP BY CATEGORY;
--10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, STUDENT_ADDRESS, ABSENCE_YN  FROM TB_STUDENT WHERE SUBSTR(STUDENT_ADDRESS, 1, 2) ='전주'AND ABSENCE_YN = 'N'AND SUBSTR(STUDENT_NO, 2, 1) = '2';


--ADDITIONAL SELECT;
--1.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도 FROM TB_STUDENT WHERE DEPARTMENT_NO = '002' ORDER BY STUDENT_NAME;
--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR WHERE LENGTH(PROFESSOR_NAME) != '3';
--3
SELECT PROFESSOR_NAME 교수이름, PROFESSOR_SSN, TRUNC((SYSDATE-TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 0, 6), 'RRMMDD'))/365) 나이 FROM TB_PROFESSOR ORDER BY TRUNC((SYSDATE-TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 0, 6), 'RRMMDD'))/365);
--4
SELECT SUBSTR(PROFESSOR_NAME, 2, 3) 이름 FROM TB_PROFESSOR;
--5
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT WHERE 19=TRUNC(MONTHS_BETWEEN(ENTRANCE_DATE, TO_DATE('19'||SUBSTR(STUDENT_SSN ,1,6),'YYYYMMDD'))/12);
--6
SELECT TO_CHAR(TO_DATE(20201225),'DAY') FROM DUAL;
--7
SELECT TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD'), TO_DATE('99/10/11','RR/MM/DD'), TO_DATE('49/10/11','RR/MM/DD') FROM DUAL;
--8
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';
--9
SELECT ROUND(AVG(POINT), 1) 평점 FROM TB_STUDENT NATURAL JOIN TB_GRADE WHERE STUDENT_NO='A517178';
--10
SELECT DEPARTMENT_NO, COUNT(DEPARTMENT_NO) FROM TB_STUDENT GROUP BY DEPARTMENT_NO ORDER BY 1; 
--11
SELECT COUNT(*) "COUNT(*)" FROM TB_STUDENT WHERE COACH_PROFESSOR_NO IS NULL;
--12
SELECT SUBSTR(TERM_NO,1,4), ROUND(AVG(POINT),1) FROM TB_GRADE WHERE STUDENT_NO='A112113' GROUP BY SUBSTR(TERM_NO,1,4) ORDER BY SUBSTR(TERM_NO,1,4);
--13
SELECT DEPARTMENT_NO 학과코드명 ,SUM(DECODE(ABSENCE_YN,'Y',1,'N',0)) "휴학생 수" FROM TB_STUDENT GROUP BY DEPARTMENT_NO ORDER BY 1;
SELECT *FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_PROFESSOR tp;
SELECT * FROM TB_GRADE tg ;
SELECT COACH_PROFESSOR_NO FROM TB_STUDENT ts; 
--14
SELECT STUDENT_NAME, COUNT(STUDENT_NAME) FROM TB_STUDENT M WHERE 1<(SELECT COUNT(STUDENT_NAME) FROM TB_STUDENT S WHERE (M.STUDENT_NAME = S.STUDENT_NAME ) GROUP BY STUDENT_NAME) GROUP BY STUDENT_NAME ORDER BY STUDENT_NAME;

--15
SELECT SUBSTR(TERM_NO,1,4) 년도, SUBSTR(TERM_NO,6,1) 학기, ROUND(AVG(POINT),1) 평점 FROM TB_GRADE WHERE STUDENT_NO='A112113' GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,6,1)) ORDER BY 1;


--Additional SELECT - OPTION 
--1.
SELECT STUDENT_NAME, STUDENT_ADDRESS FROM TB_STUDENT ORDER BY STUDENT_NAME;
--2.
SELECT STUDENT_NAME, STUDENT_SSN FROM TB_STUDENT WHERE ABSENCE_YN ='Y' ORDER BY STUDENT_SSN DESC ;
--3.
SELECT STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS FROM TB_STUDENT WHERE SUBSTR(STUDENT_NO, 1, 1)='9' AND (STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%') ORDER BY STUDENT_NAME;
--4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR WHERE DEPARTMENT_NO ='005' ORDER BY PROFESSOR_SSN;
--5.
SELECT STUDENT_NO, TO_CHAR(POINT,'9.99') FROM TB_STUDENT JOIN TB_GRADE USING(STUDENT_NO) WHERE TERM_NO='200402' AND CLASS_NO='C3118100' ORDER BY POINT DESC;
--6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME FROM TB_STUDENT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO) ORDER BY STUDENT_NAME;
--7.
SELECT CLASS_NAME, DEPARTMENT_NAME FROM TB_DEPARTMENT td JOIN TB_CLASS tc USING (DEPARTMENT_NO);
--8.
SELECT CLASS_NAME, PROFESSOR_NAME FROM TB_PROFESSOR JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO) JOIN TB_CLASS USING (CLASS_NO) ;
--9
SELECT CLASS_NAME, PROFESSOR_NAME FROM TB_PROFESSOR P JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO) JOIN TB_CLASS C USING (CLASS_NO) JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO=D.DEPARTMENT_NO) WHERE CATEGORY='인문사회';
--10
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT), 1) "전체 평점" FROM TB_STUDENT JOIN TB_GRADE USING(STUDENT_NO) WHERE DEPARTMENT_NO = '059' GROUP BY STUDENT_NO, STUDENT_NAME ORDER BY STUDENT_NO;
--11
SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME FROM TB_STUDENT M JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) JOIN TB_PROFESSOR TB ON (PROFESSOR_NO=COACH_PROFESSOR_NO) WHERE PROFESSOR_NO=(SELECT COACH_PROFESSOR_NO S FROM TB_STUDENT S WHERE STUDENT_NO='A313047') AND STUDENT_NO='A313047';
--12
SELECT STUDENT_NAME, TERM_NO FROM TB_STUDENT S JOIN TB_GRADE G USING(STUDENT_NO) JOIN TB_CLASS C USING(CLASS_NO)  WHERE SUBSTR(TERM_NO, 1, 4)='2007' AND CLASS_NAME = '인간관계론' ORDER BY 1;
--13 
SELECT CLASS_NAME, DEPARTMENT_NAME FROM TB_DEPARTMENT TD JOIN TB_CLASS TC USING(DEPARTMENT_NO) LEFT JOIN TB_CLASS_PROFESSOR TCP USING(CLASS_NO) WHERE PROFESSOR_NO IS NULL AND CATEGORY ='예체능';
--14
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수 FROM TB_STUDENT S LEFT JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO=PROFESSOR_NO) LEFT JOIN TB_DEPARTMENT D ON(P.DEPARTMENT_NO=D.DEPARTMENT_NO) WHERE S.DEPARTMENT_NO =(SELECT DEPARTMENT_NO FROM TB_DEPARTMENT td WHERE DEPARTMENT_NAME ='서반아어학과') ;
--15 
SELECT STUDENT_NAME, STUDENT_NO, DEPARTMENT_NO FROM TB_STUDENT LEFT JOIN TB_GRADE USING(STUDENT_NO) LEFT JOIN TB_DEPARTMENT  USING(DEPARTMENT_NO) WHERE ABSENCE_YN='N' GROUP BY STUDENT_NAME, STUDENT_NO, DEPARTMENT_NO HAVING AVG(POINT)>=4 ;
--16
SELECT CLASS_NO, CLASS_NAME,TRUNC(AVG(POINT),8) FROM TB_CLASS tc JOIN TB_GRADE tg USING(CLASS_NO) JOIN TB_DEPARTMENT td  USING(DEPARTMENT_NO) WHERE DEPARTMENT_NAME='환경조경학과' AND CLASS_TYPE LIKE '%전공%' GROUP BY CLASS_NO, CLASS_NAME;
--17
SELECT STUDENT_NAME, STUDENT_ADDRESS FROM TB_STUDENT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) WHERE DEPARTMENT_NO =(SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME='최경희');
--18
SELECT STUDENT_NO, STUDENT_NAME FROM (SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) FROM TB_STUDENT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) JOIN TB_GRADE tg USING(STUDENT_NO) WHERE DEPARTMENT_NAME='국어국문학과' GROUP BY STUDENT_NO, STUDENT_NAME ORDER BY AVG(POINT) DESC) WHERE ROWNUM=1;
--19
SELECT DEPARTMENT_NAME, ROUND(AVG(POINT),1) FROM TB_DEPARTMENT JOIN TB_STUDENT USING(DEPARTMENT_NO) JOIN TB_GRADE USING(STUDENT_NO) JOIN TB_CLASS USING(CLASS_NO) WHERE CATEGORY=(SELECT CATEGORY FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME ='환경조경학과') AND CLASS_TYPE LIKE '%전공%' GROUP BY DEPARTMENT_NAME ORDER BY DEPARTMENT_NAME;
;
SELECT *  FROM TB_CLASS tg;
SELECT *  FROM TB_GRADE;
SELECT *  FROM TB_PROFESSOR ;
SELECT *  FROM TB_STUDENT;
SELECT *  FROM TB_DEPARTMENT td ;




