ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--계정 생성
CREATE USER project IDENTIFIED BY "project123";

--권한 부여 : 접속, 객체생성
GRANT CONNECT, RESOURCE, CREATE VIEW TO project;

--객체생성 공간 할당
ALTER USER project DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;